api:
  host: 0.0.0.0
  port: 8000

mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "loan_risk_prediction"

feast:
  repo_path: "feature_store/feature_repo"
  redis_host: "redis"
  redis_port: 6379

logging:
  level: "info"
  format: "json"
