model:
  name: logistic_regression  
  logistic_regression:
    C: 1.0
    max_iter: 1000

  random_forest:
    n_estimators: 200
    max_depth: 10

  xgboost:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.05

training:
  test_size: 0.2
  random_state: 42
  standardization: True
